import Link from "next/link";
import Head from "next/head";
import styles from "@/styles/index.module.css";

const Apply = () => {
  return (
    <>
      <Head>
        <title>ZenZone | Apply</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/image/Hippie Monkey.jpeg" />
      </Head>
      
      <div className={styles.body}>
        <div className={styles.tag}>
          <main
            style={{
              WebkitTextStrokeWidth: "0px",
              backgroundColor: "rgb(235, 232, 229)",
              boxSizing: "inherit",
              color: "rgb(0, 30, 98)",
              display: "block",
              fontFamily: "Montserrat, sans-serif",
              fontSize: "10px",
              fontStyle: "normal",
              fontVariantCaps: "normal",
              fontVariantLigatures: "normal",
              fontWeight: "400",
              letterSpacing: "normal",
              orphans: 2,
              padding: "0px 2rem",
              textAlign: "left",
              textDecorationColor: "initial",
              textDecorationStyle: "initial",
              textDecorationThickness: "initial",
              textIndent: "0px",
              textTransform: "none",
              whiteSpace: "normal",
              widows: 2,
              wordSpacing: "0px",
            }}
          >
            <div className="Grid_row__eFXMI" style={{ display: "flex", flexFlow: "wrap", height: "inherit", margin: "0px -2rem", padding: "0px" }}>
              <div className="Grid_column__QqAhL Grid_sm-12__s7GY_" style={{ flex: "0 0 100%", margin: "0px", maxWidth: "100%", padding: "0px 2rem" }}>
                <div className="wrapper" style={{ margin: "0px auto", maxWidth: "1140px", padding: "0px" }}>
                  <div className="Grid_row__eFXMI" style={{ display: "flex", flexFlow: "wrap", height: "inherit", margin: "0px -2rem", padding: "0px" }}>
                    <div className="Grid_column__QqAhL Grid_sm-12__s7GY_" style={{ flex: "0 0 100%", margin: "0px", maxWidth: "100%", padding: "0px 2rem" }}>
                      <section className="component HowToApplyPage_apply-page__LOVqp HowToApplyPage_desktop__jrhEv" style={{ padding: "6rem 0px" }}>
                        <h1 id="how-to-apply" className="HowToApplyPage_section-title__wuN3V" style={{ fontFamily: "GT-Sectra-Fine-Bold, serif", fontSize: "6rem", fontWeight: "400", lineHeight: "1.08333", margin: "0px 0px 2.8rem", padding: "0px" }}>
                          How to apply
                        </h1>
                        <div className="Grid_row__eFXMI" style={{ display: "flex", flexFlow: "wrap", height: "inherit", margin: "0px -2rem", padding: "0px" }}>
                          <div className="Grid_column__QqAhL Grid_sm-12__s7GY_ Grid_md-6__EjGQ8" style={{ flex: "0 0 50%", margin: "0px", maxWidth: "50%", padding: "0px 2rem" }}>
                            <h3 id="create-profile" className="HowToApplyPage_sub-title__TX_sS" style={{ color: "rgb(0, 30, 98)", fontFamily: "GT-Sectra-Fine-Bold, serif", fontSize: "2rem", fontWeight: "400", lineHeight: "2.4rem", margin: "0px 0px 2.4rem", padding: "0px" }}>
                              Create profile
                            </h3>
                            <div className="HowToApplyPage_create-profile__X4yCk" style={{ margin: "0px", padding: "0px" }}>
                              <p style={{ color: "rgb(0, 30, 98)", fontSize: "1.6rem", lineHeight: "1.5", margin: "0px 0px 2.4rem", padding: "0px" }}>
                                1. Click on “Create profile” below to fill out a short registration form. If you've already done this, skip to step 2.
                              </p>
                              <p style={{ color: "rgb(0, 30, 98)", fontSize: "1.6rem", lineHeight: "1.5", margin: "0px 0px 2.4rem", padding: "0px" }}>
                                2. Verify your profile by clicking on the activation link in the email we will send you.
                              </p>
                              <p style={{ color: "rgb(0, 30, 98)", fontSize: "1.6rem", lineHeight: "1.5", margin: "0px 0px 2.4rem", padding: "0px" }}>
                                3. Return to this page to log in and start your application.
                              </p>
                              <p style={{ color: "rgb(0, 30, 98)", fontSize: "1.6rem", lineHeight: "1.5", margin: "0px 0px 2.4rem", padding: "0px" }}>
                                <strong>
                                  <button className="tertiary" style={{ color: "rgb(0, 30, 98)", cursor: "pointer", display: "inline-block", fontSize: "1.8rem", lineHeight: "1.15", margin: "0px 0px 0px -1rem", padding: "0px 1rem 0px 2.5rem", position: "relative", width: "auto" }}>
                                    Create profile
                                  </button>
                                </strong>
                              </p>
                            </div>
                          </div>
                          <div className="Grid_column__QqAhL Grid_sm-12__s7GY_ Grid_md-6__EjGQ8" style={{ flex: "0 0 50%", margin: "0px", maxWidth: "50%", padding: "0px 2rem" }}>
                            <h3 className="HowToApplyPage_sub-title__TX_sS" style={{ color: "rgb(0, 30, 98)", fontFamily: "GT-Sectra-Fine-Bold, serif", fontSize: "2rem", fontWeight: "400", lineHeight: "2.4rem", margin: "0px 0px 2.4rem", padding: "0px" }}>
                              Already registered? Please log in.
                            </h3>
                            <div className="btn-and-text-wrapper" style={{ margin: "0px", padding: "0px" }}>
                              <div className="HowToApplyPage_button-wrapper__AwkCY" style={{ margin: "0px", padding: "0px", width: "19.6rem" }}>
                                <a className="cta" style={{ backgroundColor: "rgb(0, 30, 98)", borderRadius: "0px", border: "2px solid transparent", color: "rgb(255, 255, 255)", cursor: "pointer", display: "inline-block", fontSize: "1.6rem", lineHeight: "1.5", margin: "0px", padding: "1.2rem 3.2rem", textAlign: "center", textDecoration: "none", width: "196px" }} target="_blank" rel="noopener noreferrer" href="https://www.london.edu/.netlify/functions/login?returnUrl=https%3A%2F%2Fwww.london.edu%2Finteract%3FapplyID%3D">
                                  <strong>Login</strong>
                                </a>
                              </div>
                            </div>
                          </div>
                        </div>
                      </section>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </main>
        </div>
      </div>
    </>
  );
};

export default Apply;
