import index from "@/styles/index.module.css";
import Link from "next/link";
import Head from "next/head";

const Contact = () => {
  return (
    <>
      <Head>
        <title>ZenZone | Contact</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/image/Hippie Monkey.jpeg" />
      </Head>

      {/* 
<style jsx>
    {`
   
}
    `}
</style> */}
      <div>
        <div id="body">
          <div id="tag">
            <h1>Contact Us</h1>
            <form id="form" action="/register" method="post" >
               <input type="text" name="name" id="name" placeholder="Enter your name"/>
               <input type="email" name="email" id="email" placeholder="Enter your email"/>
               <input type="number" name="'number" id="number" placeholder="Enter your number"/>
               <textarea name="application" id="application"placeholder="Enter your Application"></textarea>
               <button id="btn" type="submit">Application Submit</button>
            </form>
          </div>
        </div>
      </div>
    </>
  );
};

export default Contact;
